@startuml

package "Product" {
  ProductService - [Product]
}

database "Postgres" as postgres1 {
  [Products]
}

queue replenish

package "InventoryMock" {
  InventoryService - [InventoryMock]
}
[Product] --> [Products]
[Product] --> [InventoryService]
[Product] --> [replenish]

@enduml